openapi: 3.0.0
info:
  title: Upload
  version: '1.0'
servers:
  - url: 'https://api.danim.com'
paths:
  /upload/me:
    post:
      summary: ''
      operationId: post-upload-me
      responses:
        '200':
          description: ''
      description: 'This endpoint lets you upload files to our platform, that you may reuse elsewhere using their IDs (e.g. in the `POST` body of another API call).'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: The file content
              required:
                - file
        description: ''
components:
  schemas: {}
